#!/bin/sh

export PATH=/opt/local/libexec/ccache:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/cmake-3.1.0-Darwin64-universal/CMake.app/Contents/bin:/opt/local/bin:/opt/local/bin:/usr/local/bin
cd /Users/vagrant/slave
twistd --nodaemon -y ./buildbot.tac
