# Makefile for Solaris with cc a K&R C compiler.
# For ANSI C, use makefile.solaris .

.SUFFIXES: .c .o

# $S = ampl/solvers directory
S = ..
CC = cc
CFLAGS = -I$S -O -pic -DKR_headers
.c.o:
	$(CC) -c $(CFLAGS) $*.c

amplfunc.dll: funcaddk.c
	$(CC) -c $(CFLAGS) -pic funcaddk.c
	ld -G -o amplfunc.dll funcaddk.o

## Sample solver creation...

# $(myobjects) = list of .o files
myobjects = ....

mysolver: $(myobjects)
	$(CC) -o mysolver $(myobjects) $S/amplfunc.a -lm -ldl
