# Makefile for Solaris with cc an ANSI C compiler.

.SUFFIXES: .c .o

# $S = ampl/solvers directory
S = ..
CC = cc
CFLAGS = -I$S -O -Kpic
.c.o:
	$(CC) -c $(CFLAGS) $*.c

amplfunc.dll: funcadd.o
	ld -G -o amplfunc.dll funcadd.o

## Sample solver creation...

# $(myobjects) = list of .o files
myobjects = ....

mysolver: $(myobjects)
	$(CC) -o mysolver $(myobjects) $S/amplfunc.a -lm -ldl
