# Makefile for DEC Alpha systems under OSF1

.SUFFIXES: .c .o

# $S = ampl/solvers directory
S = ..
CC = cc
CFLAGS = -O -ieee_with_no_inexact -I$S

.c.o:
	$(CC) -c $(CFLAGS) $*.c

amplfunc.dll: funcadd.o
	ld -shared -o amplfunc.dll funcadd.o -lm -lc

## Sample solver creation...

# $(myobjects) = list of .o files
myobjects = ....

mysolver: $(myobjects)
	$(CC) -o mysolver $(myobjects) $S/amplsolver.a -lm
