# Makefile for SGI systems (under IRIX)

.SUFFIXES: .c .o

# $S = ampl/solvers directory
S = ..

CC = cc
CFLAGS = -I$S -O
.c.o:
	$(CC) -c $(CFLAGS) $*.c

amplfunc.dll: funcadd.o
	$(CC) -shared -o amplfunc.dll funcadd.o -lm

## Sample solver creation...

# $(myobjects) = list of .o files
myobjects = ....

mysolver: $(myobjects)
	$(CC) -o mysolver $(myobjects) $S/amplsolver.a -lm
