#!/bin/sh

export DISPLAY=:10

Xvfb $DISPLAY -screen 0 1024x768x16 &
sleep 1
miwm &

# This is unsecure, but the box is not publicly accessible.
mkdir $HOME/.vnc
x11vnc -storepasswd vagrant $HOME/.vnc/passwd
x11vnc -display $DISPLAY -forever -usepw &

sudo -H -u buildbot buildslave start --nodaemon /var/lib/buildbot/slave
