#!/bin/sh
# This script builds the HTML documentation and commits it to the
# gh-pages branch.

set -e
cmake .
make doc
git fetch -t git@github.com:vitaut/ampl.git +gh-pages
git checkout gh-pages
rm -rf doc
mv html doc
git add --all doc
git commit -m 'Update documentation'
