#!/bin/sh
# This script copies changes from the AMPL Solver Library on Netlib
# http://www.netlib.org/ampl into the "netlib" branch of the GitHub
# repository https://github.com/vitaut/ampl/

git stash -u
git checkout netlib
rsync -avz --delete --exclude=.git --exclude=student netlib.org::netlib/ampl/ .
chmod +x solvers/configurehere
git add .
git commit -m 'Upstream changes'
git checkout master
git stash pop
