#!/bin/sh
# This script merges changes from the AMPL Solver Library on
# Netlib http://www.netlib.org/ampl into Github repository
# https://github.com/vitaut/ampl/

# Workflow:
#
#  change   change   change
#     |        |        |
#     v        v        v
# ---------------------------- netlib.org/ampl
#       |        |        |
#       | rsync  |        |
#       v        v        v
# ---------------------------- github.com/vitaut/ampl [netlib]
#         |        |        |
#         | merge  |        |
#         v        v        v
# ---------------------------- github.com/vitaut/ampl [master]

git stash -u
git checkout netlib
rsync -avz --delete --exclude=.git --exclude=student netlib.org::netlib/ampl/ .
chmod +x solvers/configurehere
git add .
git commit -m 'Upstream changes'
git checkout master
git stash pop
