# This Python file uses the following encoding: utf-8

# if __name__ == "__main__":
#     pass

def FlatConTypes():
    res = {
    '_abs': 'Abs',
    '_acos': 'Acos',
    '_acosh': 'Acosh',
    '_alldiff': 'AllDiff',
    '_and': 'And',
    '_asin': 'Asin',
    '_asinh': 'Asinh',
    '_atan': 'Atan',
    '_atanh': 'Atanh',
    '_compl': 'Complementarity Linear',
    '_complquad': 'Complementarity Quadratic',
    '_condlineq': 'Conditional Linear \u2A75',
    '_condlinge': 'Conditional Linear \u2A7E',
    '_condlingt': 'Conditional Linear >',
    '_condlinle': 'Conditional Linear \u2A7D',
    '_condlinlt': 'Conditional Linear <',
    '_condquadeq': 'Conditional Quadratic \u2A75',
    '_condquadge': 'Conditional Quadratic \u2A7E',
    '_condquadgt': 'Conditional Quadratic >',
    '_condquadle': 'Conditional Quadratic \u2A7D',
    '_condquadlt': 'Conditional Quadratic <',
    '_cos': 'Cos',
    '_cosh': 'Cosh',
    '_count': 'Count',
    '_div': 'Div',
    '_expa': 'ExpA',
    '_exp': 'Exp',
    '_expcone': 'Exponential Cone',
    '_geomcone': 'Geometric Cone',
    '_ifthen': 'If-Then',
    '_impl': 'Implication \u21D2',
    '_indeq': 'Indicator Linear \u2A75',
    '_indge': 'Indicator Linear \u2A7E',
    '_indle': 'Indicator Linear \u2A7D',
    '_indquadeq': 'Indicator Quadratic \u2A75',
    '_indquadge': 'Indicator Quadratic \u2A7E',
    '_indquadle': 'Indicator Quadratic \u2A7D',
    '_lineq': 'Linear \u2A75',
    '_linge': 'Linear \u2A7E',
    '_linle': 'Linear \u2A7D',
    '_linrange': 'Linear Range',
    '_linfunccon': 'Linear Function',
    '_loga': 'LogA',
    '_log': 'Log',
    '_max': 'Max',
    '_min': 'Min',
    '_not': 'Not',
    '_numberofconst': 'Numberof/Const',
    '_numberofvar': 'Numberof/Var',
    '_or': 'Or',
    '_pl': 'Piecewise-Linear',
    '_pow': 'Pow',
    '_powercone': 'Power Cone',
    '_quadeq': 'Quadratic \u2A75',
    '_quadge': 'Quadratic \u2A7E',
    '_quadle': 'Quadratic \u2A7D',
    '_quadrange': 'Quadratic Range',
    '_quadcone': 'Quadratic Cone',
    '_quadfunccon': 'Quadratic Function',
    '_rotatedquadcone': 'Rotated Quadratic Cone',
    '_sos1': 'SOS1',
    '_sos2': 'SOS2',
    '_sin': 'Sin',
    '_sinh': 'Sinh',
    '_tan': 'Tan',
    '_tanh': 'Tanh',
    '_uenc': 'Unary Encoding'    }
    return res
