# For Linux

.SUFFIXES: .c .o

# $S = ampl/solvers directory
S = ..
CC = cc
GSLinclude = gsl-1.15/include
GSLlibdir = gsl-1.15/lib
CFLAGS = -fPIC -I$S -I$(GSLinclude) -O2

.c.o:
	$(CC) -c $(CFLAGS) $*.c

amplgsl.dll: amplgsl.o default.o
	$(CC) -shared -o amplgsl.dll amplgsl.o $(GSLlibdir)/libgsl.a $(GSLlibdir)/libgslcblas.a

# variant for using shared GSL libs:
#	$(CC) -shared -o amplgsl.dll amplgsl.o -L$(GSLlibdir) -lgsl -lgslcblas
