#!/bin/sh
# This script builds the HTML documentation and commits it to the
# ampl.github.io repository.

set -e
cmake .
rm -rf html ampl.github.io
make doc
git clone git@github.com:ampl/ampl.github.io.git
rm -rf ampl.github.io/*
mv html/* ampl.github.io
cd ampl.github.io
git add --all .
git commit -m 'Update documentation'
