# /****************************************************************
# Copyright (C) 1997, 1999 Lucent Technologies
# All Rights Reserved
#
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby
# granted, provided that the above copyright notice appear in all
# copies and that both that the copyright notice and this
# permission notice and warranty disclaimer appear in supporting
# documentation, and that the name of Lucent or any of its entities
# not be used in advertising or publicity pertaining to
# distribution of the software without specific, written prior
# permission.
#
# LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
# IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
# SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
# IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
# ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
# THIS SOFTWARE.
# ****************************************************************/

.SUFFIXES: .c .o
CC = cc
CFLAGS = -O
S = ..
# "S = .." assumes this directory is solvers/osl .

L = osllib/lib/libosl.so -lm
# Adjust the above L = assignment as necessary; it should specify
# the OSL library appropriately for your system and, if necessary,
# the standard math library (-lm on Unix systems).

# Add -DKR_headers to CFLAGS if your C compiler does not
# understand ANSI C function headers, e.g.
#	CFLAGS = -O -DKR_headers
# If things don't run right, you may need to change -O to -g
# so you can poke around with a debugger.
# See $S/makefile.u for other comments about CFLAGS.

# For RS6000 systems, do not use -O unless you have cc version
# at least 01.02.0000.0009 -- earlier versions are too buggy.
# Also, add -qnomaf to CFLAGS.

.c.o:
	$(CC) -c $(CFLAGS) -I$S $*.c

o = osl.o $S/funcadd0.o $S/amplsolver.a

osl: $o
	$(CC) -o osl $o $L

osl.o: $S/asl.h

$S/amplsolver.a:
	cd $S; make amplsolver.a

# make xsum.out to check for transmission errors.
# This assumes you have the xsum program, whose source
# you can get by asking research!netlib to
#	send xsum.c from f2c/src

xs0 = README.1st README.osl makefile.u makefile.vc makefile.wat\
	osl.c osl.h

xsum.out: $(xs0)
	xsum $(xs0) >xsum1.out
	cmp xsum0.out xsum1.out && mv xsum1.out xsum.out || diff xsum[01].out

# Student version...

sv = osl.o $S/sjac0dim.o $S/funcadd0.o $S/amplsolver.a

sosl: $(sv)
	$(CC) -o sosl $(sv) $L
