name:  build-and-test
run-name: ${{ github.actor }} is building "${{ github.ref_name }}"
on: [push]

env:
  CIBW_ARCHS_LINUX: auto
  CIBW_ARCHS_MACOS: x86_64 universal2
  CIBW_SKIP: pp* cp27-* *_i686 *-win32 *musllinux*
  # Fails currently
  CIBW_TEST_COMMAND: # python ${{ github.workspace }}/nl-writer2/nlwpy/tests/test.py
  CIBW_TEST_REQUIRES: # scipy numpy
#  CIBW_TEST_REQUIRES: --index-url https://pypi.ampl.com --extra-index-url https://pypi.org/simple ampl_module_base ampl_module_highs pandas numpy

jobs:
  build_native:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        with:
          package-dir: nl-writer2/nlwpy/
        env:
          CIBW_ARCHS_LINUX: ${{ env.CIBW_ARCHS_LINUX }}
          CIBW_ARCHS_MACOS: ${{ env.CIBW_ARCHS_MACOS }}
          CIBW_SKIP: ${{ env.CIBW_SKIP }}
          CIBW_TEST_COMMAND: ${{ env.CIBW_TEST_COMMAND }}
          CIBW_TEST_REQUIRES: ${{ env.CIBW_TEST_REQUIRES }}

      - uses: actions/upload-artifact@v3
        with:
          path: ./nl-writer2/nlwpy/wheelhouse/*.whl

  build_with_qemu:
    #if: github.ref == 'refs/heads/release'
    name: Build ${{ matrix.build }} wheels for ${{ matrix.arch }}
    #needs: build_native
    strategy:
      matrix:
        arch: [aarch64, ppc64le]
        build: [cp37-*, cp38-*, cp39-*, cp310-*, cp311-*, cp312-*]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        with:
          package-dir: nl-writer2/nlwpy/
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_ARCHS_MACOS: ${{ env.CIBW_ARCHS_MACOS }}
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_SKIP: ${{ env.CIBW_SKIP }}
          CIBW_TEST_COMMAND: ${{ env.CIBW_TEST_COMMAND }}
          CIBW_TEST_REQUIRES: ${{ env.CIBW_TEST_REQUIRES }}

      - uses: actions/upload-artifact@v3
        with:
          path: ./nl-writer2/nlwpy/wheelhouse/*.whl
